adam_config:
  adam_beta_1: 0.9
  adam_beta_2: 0.999
  adam_epsilon: 1.0e-07
  adam_learning_rate: 0.005

# model spec
model_path: models/UCI_N2V_baseline/
classifier_hidden_size: 24
ffn_fusion_size: 12
ffn_hidden_size: 12
gcn_fusion_size: 24
spatial_hidden_size: 24
spatial_input_dim: 64
temporal_hidden_size: 24
temporal_input_dim: 60

# training spec
num_epochs: 1000
patience: 10

major_threshold: null
train_proportion: 0.71
dev_proportion: 0.1

data_path: 'data/UCI/'
prep_data_path: 'prep_data/UCI_neg/'